import error as f

f.kill()